services:
  api_service:
    build: ./
    environment:
      MONGO_DB_URL: mongodb
      MONGO_DB_PORT: 27017
      DB_NAME: project
      UPLOAD_FILE_LOCATION: ./data
      MAX_FILE_SIZE: 104857600
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: